cp account-data-matching.md ../../developer-content/content/courses/program-security/account-data-matching.md
cp anchor-cpi.md ../../developer-content/content/courses/onchain-development/anchor-cpi.md
cp anchor-pdas.md ../../developer-content/content/courses/onchain-development/anchor-pdas.md
cp arbitrary-cpi.md ../../developer-content/content/courses/program-security/arbitrary-cpi.md
cp bump-seed-canonicalization.md ../../developer-content/content/courses/program-security/bump-seed-canonicalization.md
cp close-mint.md ../../developer-content/content/courses/token-extensions/close-mint.md
cp closing-accounts.md ../../developer-content/content/courses/program-security/closing-accounts.md
cp compressed-nfts.md ../../developer-content/content/courses/state-compression/compressed-nfts.md
cp default-account-state.md ../../developer-content/content/courses/token-extensions/default-account-state.md
cp deserialize-instruction-data.md ../../developer-content/content/courses/native-onchain-development/deserialize-instruction-data.md
cp duplicate-mutable-accounts.md ../../developer-content/content/courses/program-security/duplicate-mutable-accounts.md
cp serialize-instruction-data.md ../../developer-content/content/courses/native-onchain-development/serialize-instruction-data-frontend.md
cp deserialize-custom-data.md ../../developer-content/content/courses/native-onchain-development/deserialize-custom-data-frontend.md
cp pda.md ../../developer-content/content/courses/native-onchain-development/program-derived-addresses.md
cp intro-to-custom-on-chain-programs.md ../../developer-content/content/courses/intro-to-solana/intro-to-custom-onchain-programs.md
cp paging-ordering-filtering-data.md ../../developer-content/content/courses/native-onchain-development/paging-ordering-filtering-data-frontend.md
cp solana-mobile-dApps-with-expo.md ../../developer-content/content/courses/mobile/solana-mobile-dapps-with-expo.md
cp cpi.md ../../developer-content/content/courses/native-onchain-development/cross-program-invocations.md
cp env-variables.md ../../developer-content/content/courses/program-optimization/program-configuration.md
cp versioned-transaction.md ../../developer-content/content/courses/program-optimization/lookup-tables.md
cp vrf.md ../../developer-content/content/courses/connecting-to-offchain-data/verifiable-randomness-functions.md
cp token-extensions-on-chain.md ../../developer-content/content/courses/token-extensions/token-extensions-onchain.md
cp generalized-state-compression.md ../../developer-content/content/courses/state-compression/generalized-state-compression.md
cp getting-started.md ../../developer-content/content/courses/intro-to-solana/getting-started.md
cp hello-world-program.md ../../developer-content/content/courses/native-onchain-development/hello-world-program.md
cp interact-with-wallets.md ../../developer-content/content/courses/intro-to-solana/interact-with-wallets.md
cp intro-to-anchor-frontend.md ../../developer-content/content/courses/onchain-development/intro-to-anchor-frontend.md
cp intro-to-anchor.md ../../developer-content/content/courses/onchain-development/intro-to-anchor.md
cp intro-to-cryptography.md ../../developer-content/content/courses/intro-to-solana/intro-to-cryptography.md
cp intro-to-onchain.md ../../developer-content/content/courses/onchain-development/intro-to-onchain.md
cp intro-to-reading-data.md ../../developer-content/content/courses/intro-to-solana/intro-to-reading-data.md
cp intro-to-solana-mobile.md ../../developer-content/content/courses/mobile/intro-to-solana-mobile.md
cp intro-to-token-extensions-program.md ../../developer-content/content/courses/token-extensions/intro-to-token-extensions-program.md
cp intro-to-writing-data.md ../../developer-content/content/courses/intro-to-solana/intro-to-writing-data.md
cp local-setup.md ../../developer-content/content/courses/onchain-development/local-setup.md
cp mwa-deep-dive.md ../../developer-content/content/courses/mobile/mwa-deep-dive.md
cp nfts-with-metaplex.md ../../developer-content/content/courses/tokens-and-nfts/nfts-with-metaplex.md
cp non-transferable-token.md ../../developer-content/content/courses/token-extensions/non-transferable-token.md
cp oracles.md ../../developer-content/content/courses/connecting-to-offchain-data/oracles.md
cp owner-checks.md ../../developer-content/content/courses/program-security/owner-checks.md
cp pda-sharing.md ../../developer-content/content/courses/program-security/pda-sharing.md
cp program-architecture.md ../../developer-content/content/courses/program-optimization/program-architecture.md
cp program-security.md ../../developer-content/content/courses/native-onchain-development/program-security.md
cp program-state-management.md ../../developer-content/content/courses/native-onchain-development/program-state-management.md
cp reinitialization-attacks.md ../../developer-content/content/courses/program-security/reinitialization-attacks.md
cp rust-macros.md ../../developer-content/content/courses/program-optimization/rust-macros.md
cp security-intro.md ../../developer-content/content/courses/program-security/security-intro.md
cp signer-auth.md ../../developer-content/content/courses/program-security/signer-auth.md
cp solana-pay.md ../../developer-content/content/courses/solana-pay/solana-pay.md
cp token-extensions-in-the-client.md ../../developer-content/content/courses/token-extensions/token-extensions-in-the-client.md
cp token-extensions-metadata.md ../../developer-content/content/courses/token-extensions/token-extensions-metadata.md
cp token-program.md ../../developer-content/content/courses/tokens-and-nfts/token-program.md
cp transfer-fee.md ../../developer-content/content/courses/token-extensions/transfer-fee.md
cp type-cosplay.md ../../developer-content/content/courses/program-security/type-cosplay.md
cp durable-nonces.md ../../developer-content/content/courses/offline-transactions